/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.eichler.people.app;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        // Get message with irregular spacing
        String raw = MessageUtils.getMessage();
        // Normalize whitespace and trim
        String normalized = raw.trim().replaceAll("\\s+", " ");
        // Capitalize words using commons-text
        System.out.println(WordUtils.capitalize(normalized));
    }
}
